import { app, e, dt, time, money, who, cohortName, isCoach, isBuyer, badge, button, icon, link } from './ui.js';
import { isCoachEvaluation } from './ui.js';
export function cohortCard(cohort) {
  const completed = app.data.sessions.filter(session => session.cohortId === cohort.id && session.kind === 'cohort' && session.status === 'completed').length;
  const total = app.data.sessions.filter(session => session.cohortId === cohort.id && session.kind === 'cohort').length;
  return `<article class="cohort-card"><div class="card-top"><span class="eyebrow">12-week group practice</span>${badge(cohort.status)}</div><h3>${e(cohort.name)}</h3><p>${e(cohort.description)}</p><div class="cohort-facts"><span>${icon('cohorts')} ${cohort.enrolledCount} / ${cohort.capacity} enrolled</span><span>${icon('sessions')} ${total} × 90 min</span></div><div class="progress-label"><span>Program progress</span><span>${completed} of ${total} sessions</span></div><progress value="${completed}" max="${total || 1}" aria-label="Completed sessions"></progress><div class="card-bottom"><span>${dt(cohort.startDate, { year: undefined })} — ${dt(cohort.endDate, { year: undefined })}</span>${button('Open cohort', 'open-cohort', cohort.id, 'small')}</div></article>`;
}
export function sessionCard(session, compact = false) {
  const user = app.data.user;
  const join = session.joinable ? button('Join session ↗', 'join-session', session.id, 'primary') : `<button class="btn muted" disabled>${session.status === 'completed' ? 'Completed' : session.status === 'cancelled' ? 'Cancelled' : user.role === 'buyer' ? 'Sponsor overview' : session.hasMeetingUrl ? 'Opens 15 min before' : 'Meeting link pending'}</button>`;
  return `<article class="session-card ${compact ? 'compact' : ''}"><div class="date-tile"><span>${dt(session.startsAt, { month: 'short', day: undefined, year: undefined })}</span><strong>${dt(session.startsAt, { month: undefined, day: 'numeric', year: undefined })}</strong></div><div class="session-body"><div class="card-top"><span class="eyebrow">${e(session.kind.replaceAll('-', ' '))} · ${e(cohortName(session.cohortId))}</span>${badge(session.status)}</div><h3>${e(session.title)}</h3><p>${dt(session.startsAt, { weekday: 'long', year: undefined })} · ${time(session.startsAt)} · ${session.duration} min</p>${compact ? '' : `<div class="session-tags">${session.materials ? '<span>↗ Preparation ready</span>' : ''}${session.summary ? '<span>↗ Summary available</span>' : ''}</div>`}<div class="card-actions">${join}${button('Session details', 'session-detail', session.id, 'quiet')}${isCoach() ? button('Edit', 'edit-session', session.id, 'quiet') : ''}</div></div></article>`;
}
export function documentCard(document) {
  const scope = { cohort: 'Cohort shared', individual: 'Individual access', buyer: 'Buyer & coach', private: 'Coach private' };
  return `<article class="document-card"><div class="document-icon">${icon('resources')}</div><div class="card-top">${badge(document.scope)}<span class="eyebrow">${e(document.originalName.split('.').at(-1))}</span></div><h3>${e(document.title)}</h3><p>${e(cohortName(document.cohortId))}</p><div class="access-label">${icon(document.scope === 'private' ? 'contracts' : 'buyers')} ${scope[document.scope]}${document.participantId ? ` · ${e(who(document.participantId))}` : ''}</div><div class="card-bottom"><span>${Math.max(1, Math.round(document.size / 1024))} KB · ${e(document.phase)}</span><a class="btn small" href="/api/platform/documents/${e(document.id)}" download>Download ↓</a></div>${isCoach() ? button('Archive', 'archive-document', document.id, 'quiet small') : ''}</article>`;
}
export function reportCard(report) {
  return `<article class="report-card"><div class="card-top"><span class="eyebrow">${isCoachEvaluation(report)?'Coach evaluation':e(report.type.replaceAll('-', ' '))}</span>${badge(report.status)}</div><h3>${e(report.title)}</h3><p>${e(cohortName(report.cohortId))}</p><p class="truncate">${e(report.highlights)}</p><div class="access-label">${report.type === 'individual' ? `${e(who(report.participantId))} + coach${report.shareBuyer ? ' + buyer' : ''}` : 'Coach + buyer'}</div><div class="card-bottom"><span>${dt(report.updatedAt || report.createdAt)}</span>${button('Read report', 'view-report', report.id, 'small')}</div>${isCoach() || report.authorId === app.data.user.id ? button('Edit report', 'edit-report', report.id, 'quiet small') : ''}</article>`;
}
