import { app, e, dt, time, timeZone, localInput, money, who, cohortName, isCoach, isBuyer, field, textarea, select, check, button, badge, table, empty, modal, cohortOptions, participantOptions } from './ui.js';
import { documentCard } from './cards.js';
import { isCoachEvaluation } from './ui.js';
import { zoomSessionActions } from './zoom.js';
const hidden = (name,value) => `<input type="hidden" name="${name}" value="${e(value)}"/>`;
const selectedCohort = id => app.data.cohorts.find(c=>c.id===id||c.id===app.cohortId)||app.data.cohorts[0];
const timestampNote = `<p class="help">Date and time entries use this device’s time zone (${e(Intl.DateTimeFormat().resolvedOptions().timeZone)}). Calendar displays use the coach’s configured time zone.</p>`;
export function cohortForm(id) {
  if (!app.data.buyers.length) return modal('First, add a buyer',`<p>A cohort needs a sponsoring company.</p>${button('Add buyer','new-buyer','','primary')}`);
  const c=app.data.cohorts.find(c=>c.id===id),start=new Date(Date.now()+14*86400000),end=new Date(Date.now()+91*86400000);
  modal(c?'Configure cohort':'Create a cohort',`${hidden('id',id||'')}<div class="form-grid">${field('Cohort name','name','text',c?.name||'','maxlength="160"')}${select('Buyer / sponsoring company','buyerId',app.data.buyers.map(b=>[b.id,b.company]),c?.buyerId)}${field('Program start','startDate','datetime-local',localInput(c?.startDate||start))}${field('Program end','endDate','datetime-local',localInput(c?.endDate||end))}${field('Participant capacity','capacity','number',c?.capacity||7,'min="2" max="50"')}${field('Price per participant ($)','price','number',(c?.price??120000)/100,'min="0" step="0.01"')}${field('Program time zone','timeZone','text',c?.timeZone||timeZone())}${select('Program status','status',['draft','enrolling','active','completed'],c?.status||'enrolling')}</div>${textarea('Program overview','description',c?.description||'A twelve-week practice for mid-level managers.')}${!c?textarea('Initial participant emails (optional)','emails','','','placeholder="alex@company.com, jamie@company.com"'):''}${timestampNote}<p class="help">New cohorts receive six draft sessions. Confirm an availability poll to schedule the series. Invitations generate secure links; no email is sent.</p>`,'cohort');
}
export function buyerForm(id) {
  const b=app.data.buyers.find(b=>b.id===id);
  modal(b?'Buyer profile':'Add a buyer',`${hidden('id',id||'')}<div class="form-grid">${field('Company','company','text',b?.company||'','maxlength="160"')}${field('Contact name','contact','text',b?.contact||'','maxlength="100"')}${field('Contact email','email','email',b?.email||'')}${field('Billing email','billingEmail','email',b?.billingEmail||'')}</div>${textarea('Billing address','billingAddress',b?.billingAddress||'')}${isCoach()?textarea('Internal account notes (coach only)','notes',b?.notes||''):''}`,'buyer');
}
export function inviteForm(id) {
  const c=selectedCohort(id); if(!c)return modal('Create a cohort first',empty('No cohort available','Create the program before inviting its participants.'));
  modal('Invite your participants',`${select('Cohort','cohortId',cohortOptions(),c.id)}${textarea('Email addresses','emails','',false,'placeholder="One email per line, or separated by commas"')}<div class="upload-zone"><label class="field"><span>Or upload a CSV</span><input type="file" name="csv" accept=".csv,text/csv"/></label><p class="help">Use an “email” column. Duplicate addresses are removed; existing enrolled participants are kept.</p></div><p class="notice">Secure invitation links will appear after saving. Copy and share them yourself; no invitations are emailed.</p>`,'invite');
}
export function leadForm(id) {
  const l=app.data.leads.find(l=>l.id===id);
  modal(l?'Opportunity details':'Add an opportunity',`${hidden('id',id||'')}<div class="form-grid">${field('Contact name','name','text',l?.name||'')}${field('Email','email','email',l?.email||'')}${field('Company','company','text',l?.company||'','',false)}${field('Potential value ($)','value','number',(l?.value||0)/100,'min="0" step="0.01"')}${select('Pipeline stage','stage',['discovery','proposal','closed','lost'],l?.stage||'discovery')}</div>${textarea('Notes / proposal details','note',l?.note||'')}`,'lead');
}
export function sessionForm(id) {
  const s=app.data.sessions.find(s=>s.id===id);
  modal('Prepare the session',`${hidden('id',id)}${field('Session title','title','text',s.title)}<div class="form-grid">${field('Starts at','startsAt','datetime-local',localInput(s.startsAt),s.provider==='calendly'?'readonly':'')}${field('Duration (minutes)','duration','number',s.duration,`min="15" max="180" ${s.provider==='calendly'?'readonly':''}`)}${select('Status','status',s.provider==='calendly'?[s.status,...(s.status==='scheduled'?['completed']:[])]:['draft','scheduled','completed','cancelled'],s.status)}${field('Zoom / Meet / video URL','meetingUrl','url',s.meetingUrl||'','placeholder="https://…"',false)}</div>${timestampNote}${textarea('Pre-session materials / preparation','materials',s.materials)}${textarea('Post-session summary (shared)','summary',s.summary)}${textarea('Session notes (coach-private)','privateNotes',s.privateNotes)}<p class="help">Private notes are never returned to participant or buyer accounts. Joining opens 15 minutes before the scheduled start.</p>`,'session');
}
export function sessionDetail(id) {
  const s=app.data.sessions.find(s=>s.id===id);
  const docs=app.data.documents.filter(d=>d.sessionId===id);
  modal(s.title,`<div class="detail-meta">${badge(s.status)}<span>${e(cohortName(s.cohortId))}</span></div><p>${dt(s.startsAt,{weekday:'long'})} · ${time(s.startsAt)} · ${s.duration} min · ${e(timeZone())}</p><div class="card-actions">${s.joinable?button('Join session ↗','join-session',id,'primary'):''}<a class="btn" href="/api/platform/sessions/${e(id)}/calendar">Add to Google / Outlook (.ics) ↓</a>${isCoach()?button('Edit session','edit-session',id,'quiet'):''}${s.provider==='calendly'&&s.status==='scheduled'?['rescheduleUrl','cancelUrl'].map(key=>s[key]?`<a class="btn quiet" href="${e(s[key])}" target="_blank" rel="noopener noreferrer">${key==='rescheduleUrl'?'Reschedule':'Cancel'} in Calendly ↗</a>`:'').join(''):''}</div>${!s.hasMeetingUrl&&s.status==='scheduled'?'<p class="help">Your coach has not added a meeting link yet.</p>':''}<section class="material-block"><span class="eyebrow">Before the session</span><h3>A little preparation.</h3><p class="pre-wrap">${e(s.materials||'No preparation has been assigned yet.')}</p></section><section class="material-block"><span class="eyebrow">After the session</span><h3>What to carry forward.</h3><p class="pre-wrap">${e(s.summary||'The session summary will appear here when your coach adds it.')}</p></section>${zoomSessionActions(s)}${docs.length?`<div class="card-grid two">${docs.map(documentCard).join('')}</div>`:''}${isCoach()?`<section class="private-block"><span class="eyebrow">Coach-private notes</span><p class="pre-wrap">${e(s.privateNotes||'No private notes yet.')}</p></section>`:''}${(isCoach()||s.participantId===app.data.user.id)&&s.status==='scheduled'&&s.provider!=='calendly'?button('Cancel session','cancel-session',s.id,'danger quiet'):''}`);
}
export function pollForm() {
  const c=selectedCohort();if(!c)return modal('Create a cohort first',empty('No cohort available'));
  modal('Create an availability poll',`${select('Cohort','cohortId',cohortOptions(),c.id)}${field('Poll title','title','text','Choose our working time')}${field('Response deadline','deadline','datetime-local',localInput(Date.now()+3*86400000))}<fieldset class="proposed-slots"><legend>Proposed times · at least five</legend>${Array.from({length:7},(_,i)=>field(`Option ${i+1}`,'slots','datetime-local',localInput(Date.now()+(7+i)*86400000),'',i<5)).join('')}</fieldset>${timestampNote}`,'poll');
}
export function respondPoll(id) {
  const poll=app.data.polls.find(p=>p.id===id),mine=poll.responses.find(r=>r.userId===app.data.user.id);
  const options=[['','Choose a time'],...poll.slots.map((slot,index)=>[String(index),`${dt(slot,{weekday:'short'})} · ${time(slot)}`])];
  modal('Your five preferred times',`${hidden('id',id)}<p>${e(poll.title)}. Rank five different times, starting with the one that works best. Times are shown in ${e(timeZone())}.</p>${Array.from({length:5},(_,index)=>select(`${['First','Second','Third','Fourth','Fifth'][index]} choice`,`rank${index}`,options,mine?String(mine.choices[index]):'','required')).join('')}`,'poll-response');
}
export function pollMatrix(id) {
  const poll=app.data.polls.find(p=>p.id===id);
  const roster=app.data.enrollments.filter(r=>r.cohortId===poll.cohortId&&r.status==='enrolled');
  const totals=poll.slots.map((_,i)=>poll.responses.reduce((sum,r)=>sum+(r.choices.includes(i)?5-r.choices.indexOf(i):0),0));
  const winner=totals.indexOf(Math.max(...totals));
  modal('Availability response matrix',`<p>${e(poll.title)} · ${poll.responseCount} responses. Scores award 5 points for first preference, down to 1 for fifth.</p>${table(['Participant',...poll.slots.map((s,i)=>`Option ${i+1}`)],roster.map(r=>{const response=poll.responses.find(x=>x.userId===r.userId);return `<tr><td>${e(who(r.userId))}</td>${poll.slots.map((_,i)=>`<td class="rank-cell ${response?.choices.includes(i)?'ranked':''}">${response?.choices.includes(i)?response.choices.indexOf(i)+1:'—'}</td>`).join('')}</tr>`;}).concat(`<tr class="total-row"><td>Weighted score</td>${totals.map(t=>`<td>${t}</td>`).join('')}</tr>`))}<div class="poll-options">${poll.slots.map((s,i)=>`<div><span><strong>Option ${i+1}</strong> · ${dt(s)} · ${time(s)}${i===winner&&poll.responseCount?' <span class="badge suggested">Highest score</span>':''}</span>${poll.status==='open'?`<button class="btn small" data-action="confirm-poll" data-id="${e(id)}" data-index="${i}">Confirm this time</button>`:i===poll.winningIndex?badge('confirmed'):''}</div>`).join('')}</div><p class="help">Confirming schedules this cohort’s remaining sessions at the selected local time, checks conflicts across the series, and notifies participants in the app.</p>`);
}
export function documentForm(id) {
  const c=selectedCohort(id);if(!c)return modal('Create a cohort first',empty('No cohort available'));
  modal('Share a document',`${select('Cohort','cohortId',cohortOptions(),c.id,'data-dependent-cohort')}${field('Document title','title','text','','maxlength="160"')}${field('File (up to 3 MB)','file','file','','accept=".pdf,.txt,.docx,.xlsx,.png,.jpg,.jpeg"')}${select('Who can access it?','scope',[['cohort','Cohort members + buyer'],['individual','One participant + coach'],['buyer','Buyer + coach'],['private','Coach only']],'cohort')}${select('Individual recipient (for individual access)','participantId',[['','Choose participant'],...participantOptions(c.id)],'','data-participant-select')}${select('Assign to a session (optional)','sessionId',[['','Shared resource library'],...app.data.sessions.filter(s=>s.cohortId===c.id).map(s=>[s.id,s.title])],'','data-session-select')}${select('Content type','phase',[['resource','Shared resource'],['before','Before the session'],['after','After the session']])}<p class="help">Access is enforced for every download, including direct links.</p>`,'document');
}
export function reportForm(id, defaults = {}) {
  const r=app.data.reports.find(r=>r.id===id)||defaults,c=selectedCohort(r?.cohortId);if(!c)return modal('No cohort available',empty('Join or create a cohort first'));
  modal(isCoach()?'Compose a report':'Write a reflection',`${hidden('id',id||'')}${select('Cohort','cohortId',cohortOptions(),r?.cohortId||c.id,'data-dependent-cohort')}${isCoach()?`<div class="form-grid">${select('Report type','type',[['individual','Participant evaluation'],['cohort','Cohort summary'],['end-of-program','End-of-program report']],r?.type||'individual')}${select('Participant (individual reports)','participantId',participantOptions(r?.cohortId||c.id),r?.participantId||'','data-participant-select')}</div>`:hidden('type','individual')}${field('Report title','title','text',r?.title||'')}${textarea(isCoach()?'Strengths & observations':'Highlights / reflection','highlights',r?.highlights||'',true)}${textarea(isCoach()?'Progress & development areas':'Progress against goals','progress',r?.progress||'')}${textarea(isCoach()?'Recommended next steps':'Next steps / practice plan','nextSteps',r?.nextSteps||'')}${check('Share this individual report with the buyer / manager','shareBuyer',r?.shareBuyer)}${select('Publication status','status',[['draft','Draft — not shared yet'],['published','Publish to selected viewers']],r?.status||'draft')}<p class="help">Published individual reports are visible to the participant and coach. Select buyer sharing to include their sponsor.</p>`,'report');
}
export function evaluationForm(enrollmentId) {
  const enrollment=app.data.enrollments.find(item=>item.id===enrollmentId);
  if(!enrollment)return modal('Participant unavailable',empty('Choose a participant in your cohort.'));
  reportForm(undefined,{cohortId:enrollment.cohortId,participantId:enrollment.userId,type:'individual',title:`${who(enrollment.userId)} / Coach evaluation`,shareBuyer:true});
}
export function reportDetail(id) {
  const r=app.data.reports.find(r=>r.id===id);
  if(!r)return modal('Report unavailable',empty('This report is not available to your account.'));
  const evaluation=isCoachEvaluation(r),labels=evaluation?['Strengths & coach observations','Progress & development areas','Recommended next steps']:['Highlights & reflection','Progress against goals','Next steps & practice plan'];
  modal(r.title,`<article class="print-document"><div class="eyebrow">GoCoach · ${evaluation?'Coach evaluation':e(r.type)}</div><h3>${e(r.title)}</h3><p>${e(cohortName(r.cohortId))}${r.participantId?` · ${e(who(r.participantId))}`:''}</p>${evaluation?`<p class="help">Evaluated by ${e(who(r.authorId))} · ${dt(r.updatedAt||r.publishedAt||r.createdAt)}</p>`:''}${['highlights','progress','nextSteps'].map((key,i)=>`<section class="material-block"><h3>${labels[i]}</h3><p class="pre-wrap">${e(r[key]||'No additional notes.')}</p></section>`).join('')}<p class="help">${r.status==='draft'?'Draft · not shared':r.type==='individual'?`Shared with participant + coach${r.shareBuyer?' + buyer / manager':''}`:'Shared with coach + buyer'} · ${dt(r.updatedAt||r.createdAt)}</p></article>${button('Print / save as PDF','print','','primary')}`);
}
export function surveyForm(id) {
  const s=app.data.surveys.find(s=>s.id===id),c=selectedCohort(s?.cohortId);if(!c)return modal('Create a cohort first',empty('No cohort available'));
  const defaults=['I feel confident in my leadership practice.','I can lead people through change.','I collaborate effectively across teams.','I have meaningful retention conversations.','I have a clear plan for continued growth.'];
  modal('Configure a reflection survey',`${hidden('id',id||'')}${select('Cohort','cohortId',cohortOptions(),s?.cohortId||c.id)}${field('Survey title','title','text',s?.title||'Leadership reflection')}<div class="form-grid">${select('Measurement stage','stage',[['pre','Pre-program'],['mid','Mid-program'],['post','Post-program']],s?.stage||'pre')}${select('Status','status',['draft','open','closed'],s?.status||'draft')}</div>${field('Response deadline','deadline','datetime-local',localInput(s?.deadline||Date.now()+7*86400000))}${textarea('Rating questions (one per line)','questions',(s?.questions||defaults).join('\n'),true)}<p class="help">Each item uses a 1–5 scale. Questions are locked once responses arrive.</p>`,'survey');
}
export function respondSurvey(id) {
  const s=app.data.surveys.find(s=>s.id===id),mine=s.responses.find(r=>r.userId===app.data.user.id);
  modal(s.title,`${hidden('id',id)}<p>1 = strongly disagree · 5 = strongly agree. Your coach sees your responses; your buyer sees aggregates.</p>${s.questions.map((question,i)=>`<fieldset class="rating"><legend>${e(question)}</legend>${[1,2,3,4,5].map(score=>`<label><input type="radio" name="answer${i}" value="${score}" required ${mine?.answers[i]===score?'checked':''}/><span>${score}</span></label>`).join('')}</fieldset>`).join('')}${textarea('Anything else you’d like your coach to know?','reflection',mine?.reflection||'')}`,'survey-response');
}
export function surveyResults(id) {
  const s=app.data.surveys.find(s=>s.id===id),mine=s.responses.find(r=>r.userId===app.data.user.id);
  modal(s.title,`<p>${e(s.stage)}-program · ${s.responseCount} responses received.</p>${table(['Question',isCoach()||isBuyer()?'Average / 5':'My rating / 5'],s.questions.map((q,i)=>`<tr><td>${e(q)}</td><td><strong>${isCoach()||isBuyer()?s.averages[i]?.toFixed(1)||'—':mine?.answers[i]||'—'}</strong></td></tr>`))}${isBuyer()?'<p class="help">Only aggregate ratings are shared with the buyer. Individual response text stays private to the participant and coach.</p>':s.responses.map(r=>`<section class="material-block"><h3>${e(who(r.userId))}</h3><p>Ratings: ${r.answers.join(' · ')}</p><p class="pre-wrap">${e(r.reflection||'No written reflection.')}</p></section>`).join('')}`);
}
