import { app, e, dt, money, who, buyerName, cohortName, isCoach, isBuyer, scoped, badge, button, icon, empty, heading, panelHead, table, stat, link, field, select, check } from './ui.js';
import { calendlySettings } from './calendly.js';
import { zoomSettings } from './zoom.js';
export function billing() {
  const invoices=scoped(app.data.invoices), year=new Date().getFullYear();
  const received=invoices.flatMap(i=>i.payments).filter(p=>new Date(p.date).getFullYear()===year).reduce((n,p)=>n+p.amount,0);
  const balances=invoices.filter(i=>i.status!=='draft').reduce((n,i)=>n+i.balance,0);
  const sums = (items, key, title) => { const rows=items.map(item=>({name:item.name||item.company,value:invoices.filter(i=>i[key]===item.id).flatMap(i=>i.payments).filter(p=>new Date(p.date).getFullYear()===year).reduce((n,p)=>n+p.amount,0)})); const max=Math.max(1,...rows.map(r=>r.value)); return `<section class="panel">${panelHead(title,`${year} · recorded payments`)}<div class="revenue-bars">${rows.map(r=>`<div class="revenue-row"><div><span>${e(r.name)}</span><strong>${money(r.value)}</strong></div><div class="bar-track"><span style="width:${r.value/max*100}%"></span></div></div>`).join('')||'<p>No payment records yet.</p>'}</div></section>`; };
  return `${heading('Payments & operations',isCoach()?'Billing & revenue':'Invoices & payments','Invoices, balances, and a history of payments recorded. No payment processor is connected.',isCoach()?button('Create an invoice +','new-invoice','','primary'):'')}<div class="stats three">${stat('Received / YTD',money(received),String(year),'green')}${stat('Outstanding',money(balances),'On issued invoices','orange')}${stat('Overdue invoices',invoices.filter(i=>i.displayStatus==='overdue').length,'Awaiting payment','plum')}</div>${isCoach()?`<div class="dashboard-grid">${sums(app.data.cohorts,'cohortId','Revenue by cohort')}${sums(app.data.buyers,'buyerId','Revenue by buyer')}</div>`:''}<section class="panel">${panelHead('Invoices & payment history')}${table(['Invoice','Buyer / cohort','Due','Amount','Balance','Status',''],invoices.map(i=>`<tr><td><strong>${e(i.number)}</strong><span>${e(i.title)}</span></td><td>${e(buyerName(i.buyerId))}<span>${e(cohortName(i.cohortId))}</span></td><td>${dt(i.dueDate)}</td><td>${money(i.amount)}</td><td>${money(i.balance)}</td><td>${badge(i.displayStatus)}</td><td>${button('View','view-invoice',i.id,'small')}</td></tr>`))}${!invoices.length?empty('No invoices yet','Issued invoices appear in the buyer’s account.'):''}</section>`;
}
export function contracts() {
  return `${heading('Agreements & review','Agreements','Generate a program agreement, request buyer review, and record a local acknowledgement.',isCoach()?button('Create an agreement +','new-contract','','primary'):'')}<div class="notice">${icon('contracts')}<p>Local review workflow. DocuSign is not connected; an acknowledgement here is not a DocuSign signature.</p></div><div class="card-grid">${scoped(app.data.contracts).map(c=>`<article class="cohort-card"><div class="card-top"><span class="eyebrow">${e(c.company)}</span>${badge(c.status)}</div><h3>${e(c.title)}</h3><p>${e(c.programName)}<br/>${dt(c.startDate)} — ${dt(c.endDate)}</p><strong class="agreement-amount">${money(c.amount)}</strong><div class="card-actions">${button('Review agreement','view-contract',c.id,'primary')}${isCoach()&&c.status==='draft'?button('Edit draft','edit-contract',c.id,'quiet'):''}</div>${c.acknowledgement?`<div class="access-label">Acknowledged by ${e(c.acknowledgement.name)} · ${dt(c.acknowledgement.at)}</div>`:''}</article>`).join('')||empty('Start with shared expectations','Draft an agreement for the buyer to review in their workspace.')}</div>`;
}
export function messages() {
  const user=app.data.user;
  const people=app.data.users.filter(person=>person.id!==user.id&&(isCoach()||person.role==='coach'||(isBuyer()?person.role==='participant':person.role==='buyer')));
  return `${heading('Communication','Messages','Private messages inside the workspace. Messages are not sent by email.',button('New message +','new-message','','primary'))}<div class="messages-grid"><aside class="panel">${panelHead('People you can reach')}<div class="people-list">${people.map(person=>`<button data-action="message-person" data-id="${e(person.id)}"><span class="avatar">${e(person.name.split(' ').map(w=>w[0]).slice(0,2).join(''))}</span><span><strong>${e(person.name)}</strong><small>${e(person.role)}</small></span>${icon('arrow')}</button>`).join('')}</div></aside><section class="panel">${panelHead('Your conversations')}<div class="message-list">${[...app.data.messages].sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).map(m=>`<article class="message ${m.senderId===user.id?'outgoing':''}"><div><strong>${e(who(m.senderId))}</strong><span>to ${e(who(m.recipientId))} · ${dt(m.createdAt,{hour:'numeric',minute:'2-digit'})}</span></div><p class="pre-wrap">${e(m.body)}</p>${button('Reply','message-person',m.senderId===user.id?m.recipientId:m.senderId,'quiet small')}</article>`).join('')||empty('A good question opens a door','Send your coach or buyer a message to get started.')}</div></section></div>`;
}
export function notifications() {
  return `${heading('Notification center','Notifications','Poll deadlines, reports, session reminders, and new messages.',button('Mark all as read','read-all','','primary'))}<section class="panel notification-list">${app.data.notifications.map(n=>`<article class="notification ${n.read?'read':''}"><span class="tiny-dot ${n.read?'':'orange'}"></span><div><strong>${e(n.title)}</strong><p>${e(n.body)}</p><small>${dt(n.createdAt,{hour:'numeric',minute:'2-digit'})}</small></div><a class="btn quiet" href="#${e(n.target)}">Open ${icon('arrow')}</a>${!n.read?button('Mark read','read-notification',n.id,'quiet small'):badge('read')}</article>`).join('')||empty('You’re all caught up','New activity will appear here.')}</section>`;
}
export function reminders() {
  const settings=app.data.settings;
  return `${heading('Reminders & nudges','Reminders',app.data.storage==='postgres'?'Netlify checks due reminders every five minutes.':'The server checks due reminders every minute while it is running.',button('Check due reminders','run-reminders','','primary'))}<div class="notice"><p>In-app reminders are live. Email sequences produce unsent local drafts until an email provider is connected.</p></div><section class="panel">${panelHead('Reminder preferences')}<form data-form="reminder-settings" class="settings-form">${field('Reminder sequence (hours before each event)','reminderOffsets','text',(settings.reminderOffsets||[settings.reminderHours]).join(', '),'placeholder="72, 24, 2"')}<p class="help">Enter up to eight steps, such as 72, 24, 2. Each step runs once per recipient. After downtime, only the most relevant step is generated.</p>${check('Enable session, poll, and survey reminders','remindersEnabled',settings.remindersEnabled)}<button type="submit" class="btn primary">Save reminder preferences</button><p class="form-error" role="alert" hidden></p></form></section><section class="panel">${panelHead('Email draft queue','A record of prepared invitations and reminders. None have been sent.','<a class="btn small" href="/api/platform/export?collection=outbox">Export drafts ↓</a>')}${table(['Recipient','Subject','Prepared','Delivery'],app.data.outbox.map(item=>`<tr><td>${e(item.recipient)}</td><td><strong>${e(item.subject)}</strong><span>${e(item.body)}</span></td><td>${dt(item.createdAt)}</td><td>${badge(item.status)}</td></tr>`))}${!app.data.outbox.length?'<p class="muted-copy">Invitations and due reminders will create drafts here.</p>':''}</section>`;
}
export function integrations() {
  const s=app.data.settings;
  return `${heading('Scheduling & integrations','Settings & connections','Connect Calendly for discovery calls and participant 1:1s.')} ${calendlySettings()} ${zoomSettings()} ${app.data.calendly?.enabled?'':`<section class="panel">${panelHead('Bookable availability','Discovery calls and individual 1:1s share this calendar. All slots are 30 minutes.')}<form data-form="availability-settings" class="settings-form"><div class="form-grid">${field('Time zone','timeZone','text',s.timeZone)}${field('Start hour (0–23)','startHour','number',s.startHour,'min="0" max="22"')}${field('End hour (0–23)','endHour','number',s.endHour,'min="1" max="23"')}</div><fieldset class="weekdays"><legend>Bookable days</legend>${['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map((day,i)=>`<label><input type="checkbox" name="weekdays" value="${i}" ${s.weekdays.includes(i)?'checked':''}/>${day}</label>`).join('')}</fieldset><div><button class="btn primary" type="submit">Save availability</button><a class="btn quiet" href="/book.html">Open discovery booking ↗</a></div><p class="form-error" role="alert" hidden></p></form></section>`}<div class="card-grid">${app.data.integrations.filter(item=>item.id!=='video').map(item=>`<article class="cohort-card"><div class="card-top"><span class="connection-icon">${icon('integrations')}</span>${badge(item.status)}</div><h3>${e(item.name)}</h3><p>${e(item.description)}</p>${['google','outlook'].includes(item.id)?link('Go to session calendar files','sessions','quiet'):''}</article>`).join('')}</div><section class="panel">${panelHead('Integration event hooks','Local event records for additional provider adapters. Calendly uses its own verified webhook connection.','<a class="btn small" href="/api/platform/export?collection=hooks">Export event hooks ↓</a>')}${table(['Event','Created','State'],app.data.hooks.slice(-15).reverse().map(h=>`<tr><td><code>${e(h.kind)}</code></td><td>${dt(h.createdAt)}</td><td>${badge(h.status)}</td></tr>`))}${!app.data.hooks.length?'<p class="muted-copy">Booking, schedule, and agreement actions create hooks here.</p>':''}</section>`;
}
