import { app, e, dt, time, timeZone, money, who, buyerName, cohortName, isCoach, isBuyer, scoped, badge, button, icon, empty, heading, panelHead, table, stat, link } from './ui.js';
import { cohortCard, sessionCard, documentCard, reportCard } from './cards.js';
import { isCoachEvaluation } from './ui.js';

/** Latest coach-written evaluation for each participant in the selected cohort(s).
 * @param {string} cohortId @returns {Array<{enrollment:any, report:any}>} */
export function participantEvaluations(cohortId = app.cohortId) {
  const reports = app.data.reports.filter(isCoachEvaluation).sort((a, b) =>
    (b.updatedAt || b.publishedAt || b.createdAt).localeCompare(a.updatedAt || a.publishedAt || a.createdAt));
  return app.data.enrollments.filter(enrollment => !cohortId || enrollment.cohortId === cohortId).map(enrollment => ({
    enrollment,
    report: reports.find(report => report.cohortId === enrollment.cohortId && report.participantId === enrollment.userId),
  }));
}

/** @param {string} cohortId @param {boolean} compact @returns {string} */
export function evaluationSection(cohortId = app.cohortId, compact = false) {
  const rows = participantEvaluations(cohortId);
  const visible = compact ? rows.slice(0, 4) : rows;
  return `<section class="panel evaluation-panel">${panelHead('Coach evaluations', isCoach() ? 'Write and share an assessment for each participant.' : 'Your participants’ progress, assessed by their coach.', compact ? link('View all', 'evaluations', 'quiet') : '')}
    <div class="evaluation-list">${visible.map(({ enrollment, report }) => {
      const name = who(enrollment.userId);
      const status = report ? report.status === 'draft' ? 'Draft' : report.shareBuyer ? 'Shared with buyer' : 'Participant only' : 'Not yet shared';
      return `<article class="evaluation-row"><div class="evaluation-person"><span class="avatar" aria-hidden="true">${e(name.split(' ').map(word => word[0]).slice(0, 2).join(''))}</span><div><h3>${e(name)}</h3><p>${e(cohortName(enrollment.cohortId))}</p>${badge(enrollment.status)}</div></div>
        <div class="evaluation-summary"><span class="badge ${report?.status === 'published' ? 'published' : ''}">${status}</span>${report ? `<p class="evaluation-excerpt">${e(report.highlights)}</p><small>${e(who(report.authorId))} · ${dt(report.updatedAt || report.publishedAt || report.createdAt)}</small>` : `<p>${enrollment.status === 'invited' ? 'The participant has been invited. Their coach’s evaluation will appear here once shared.' : 'An evaluation will appear here when the coach publishes it to your account.'}</p>`}</div>
        <div class="evaluation-actions">${report ? button('Read evaluation', 'view-report', report.id, 'small') : ''}${isCoach() ? report?.status === 'draft' ? button('Continue draft', 'edit-report', report.id, 'quiet small') : button('Write evaluation', 'new-evaluation', enrollment.id, 'quiet small') : ''}</div></article>`;
    }).join('') || empty('No participants in this view', 'Participants and their coach’s shared evaluations appear here once a cohort has a roster.')}</div>
    ${compact && rows.length > visible.length ? `<p class="help">Showing ${visible.length} of ${rows.length} participant enrollments.</p>` : ''}</section>`;
}

export function evaluations() {
  return `${heading('Individual progress', 'Participant evaluations', isCoach() ? 'Review each person’s progress and publish your assessment to the participant and buyer.' : 'Coach-written observations and next steps for the people in your cohorts.')}${evaluationSection()}`;
}
export function overview() {
  const d = app.data, coach = isCoach(), buyer = isBuyer();
  const cohorts = scoped(d.cohorts), sessions = scoped(d.sessions);
  const upcoming = sessions.filter(s => s.status === 'scheduled' && Date.parse(s.startsAt) + s.duration * 60000 > Date.now()).sort((a,b) => a.startsAt.localeCompare(b.startsAt));
  const pendingPolls = scoped(d.polls).filter(p => p.status === 'open' && Date.parse(p.deadline) > Date.now());
  const reports = scoped(d.reports).filter(r => r.status === 'published');
  const invoices = scoped(d.invoices);
  const ytd = invoices.flatMap(i => i.payments).filter(p => new Date(p.date).getFullYear() === new Date().getFullYear()).reduce((sum,p) => sum + p.amount, 0);
  const stats = coach ? [stat('Active cohorts', cohorts.filter(c => c.status === 'active').length, `${cohorts.length} programs in your practice`, 'plum'), stat('Enrolled participants', cohorts.reduce((n,c) => n+c.enrolledCount,0), 'Across active and enrolling cohorts', 'green'), stat('Revenue / YTD', money(ytd), 'Recorded payments received', 'ochre'), stat('Pipeline value', money(d.leads.filter(l => ['discovery','proposal'].includes(l.stage)).reduce((sum,l) => sum+l.value,0)), 'Open discovery + proposals', 'orange')] : buyer ? [stat('Your cohorts', cohorts.length, 'Programs in your organization', 'plum'), stat('People enrolled', cohorts.reduce((n,c) => n+c.enrolledCount,0), 'Across your cohorts', 'green'), stat('Published reports', reports.length, 'Shared with your account', 'ochre'), stat('Outstanding', money(invoices.reduce((sum,i) => sum+i.balance,0)), 'Balance on issued invoices', 'orange')] : [stat('Your cohorts', cohorts.length, 'A shared practice', 'plum'), stat('Next session', upcoming.length ? dt(upcoming[0].startsAt, {year:undefined}) : 'Not set', upcoming.length ? time(upcoming[0].startsAt) : 'Your coach will confirm', 'green'), stat('Open polls', pendingPolls.length, 'Your top five preferred times', 'ochre'), stat('Your reflections', reports.length, 'Progress you can return to', 'orange')];
  return `${heading('Practice overview', `${`Welcome back, ${e(d.user.name.split(' ')[0])}`}`, coach ? 'Your cohorts, upcoming sessions, and priorities in one place.' : buyer ? 'A clear view of your people and their progress.' : 'Prepare for your next session and track your progress.', coach ? button('Create a cohort +','new-cohort','','primary') : !buyer ? button('Book a 1:1 ↗','book-one-to-one','','primary') : '')}<div class="stats">${stats.join('')}</div>${buyer?evaluationSection(app.cohortId,true):''}<div class="dashboard-grid"><section class="panel">${panelHead(coach ? 'Next on the calendar' : 'Your next session', timeZone(), link('All sessions','sessions','quiet'))}${upcoming.length ? sessionCard(upcoming[0], true) : empty('Room for the next step', 'Confirmed sessions will appear here.', coach ? link('Review availability','availability') : '')}<div class="schedule-strip">${upcoming.slice(1,4).map(s => `<button data-action="session-detail" data-id="${e(s.id)}"><span>${dt(s.startsAt,{year:undefined})}</span><strong>${e(s.title)}</strong><small>${time(s.startsAt)}</small></button>`).join('')}</div></section><section class="panel attention">${panelHead('Needs attention', 'Upcoming deadlines and unread updates')}${pendingPolls.slice(0,2).map(p => `<a class="attention-row" href="#availability"><span class="tiny-dot orange"></span><div><strong>${e(p.title)}</strong><span>Due ${dt(p.deadline)}</span></div>${icon('arrow')}</a>`).join('')}${d.notifications.filter(n => !n.read).slice(0,3).map(n => `<a class="attention-row" href="#${e(n.target)}"><span class="tiny-dot green"></span><div><strong>${e(n.title)}</strong><span>${e(n.body)}</span></div>${icon('arrow')}</a>`).join('')}${!pendingPolls.length&&!d.notifications.some(n=>!n.read)?'<p class="muted-copy">You’re all caught up.</p>':''}</section></div><section>${panelHead('Your cohorts', 'Enrollment and program progress', link('View all','cohorts','quiet'))}<div class="card-grid">${cohorts.map(cohortCard).join('') || empty('Your first cohort starts here', 'Create a program and invite its participants.')}</div></section>`;
}
export function pipeline() {
  const leads = app.data.leads || [];
  return `${heading('Client acquisition', 'Client pipeline', 'Move each relationship from discovery to proposal to a confirmed engagement.', button('Add opportunity +','new-lead','','primary'))}<div class="pipeline-board">${['discovery','proposal','closed','lost'].map(stage => { const records = leads.filter(l => l.stage === stage); return `<section class="pipeline-column"><div class="pipeline-head"><h2>${{discovery:'Discovery',proposal:'Proposals',closed:'Closed / won',lost:'Closed / lost'}[stage]}</h2><span>${records.length}</span></div><div class="pipeline-total">${money(records.reduce((n,l)=>n+l.value,0))}</div>${records.map(lead => `<article class="lead-card"><span class="eyebrow">${e(lead.company || 'Individual inquiry')}</span><h3>${e(lead.name)}</h3><p>${e(lead.note || 'A first conversation is the next step.')}</p><strong>${money(lead.value)}</strong><label class="field"><span class="sr-only">Stage for ${e(lead.name)}</span><select data-lead-stage="${e(lead.id)}">${['discovery','proposal','closed','lost'].map(s => `<option value="${s}" ${s===stage?'selected':''}>${s}</option>`).join('')}</select></label>${button('Open opportunity','edit-lead',lead.id,'quiet small')}</article>`).join('') || '<p class="lane-empty">New possibilities land here.</p>'}</section>`; }).join('')}</div><section class="panel mailing-panel">${panelHead('The mailing list', 'Explicit opt-ins saved locally. Email delivery is not connected.', '<a class="btn small" href="/api/platform/export?collection=subscribers">Export list ↓</a>')}${table(['Email','Preference','Consent recorded'],(app.data.subscribers || []).map(s=>`<tr><td>${e(s.email)}</td><td>${badge(s.status)}</td><td>${dt(s.consentAt)}</td></tr>`))}${!app.data.subscribers?.length ? '<p class="muted-copy">The mailing-list form on the public website adds subscribers here.</p>' : ''}</section>`;
}
export function cohorts() {
  return `${heading('Cohort setup & enrollment', 'Cohorts', 'Programs built around a shared direction.', isCoach() ? button('Create a cohort +','new-cohort','','primary') : '')}<div class="card-grid">${scoped(app.data.cohorts).map(cohortCard).join('') || empty('No cohorts here yet', 'Your coach will invite you when the next cohort is ready.')}</div>`;
}
export function cohortDetail(id) {
  const cohort = app.data.cohorts.find(c=>c.id===id);
  if (!cohort) return empty('Cohort not found','This program is not available to your account.',link('Back to cohorts','cohorts'));
  const roster = app.data.enrollments.filter(item=>item.cohortId===id);
  const sessions = app.data.sessions.filter(item=>item.cohortId===id).sort((a,b)=>a.startsAt.localeCompare(b.startsAt));
  const docs = app.data.documents.filter(item=>item.cohortId===id);
  return `<a class="back-link" href="#cohorts">← All cohorts</a>${heading(buyerName(cohort.buyerId),e(cohort.name),cohort.description,isCoach()?button('Configure cohort','edit-cohort',id,'primary'):'')}<div class="stats">${stat('Program',`${dt(cohort.startDate,{year:undefined})} — ${dt(cohort.endDate,{year:undefined})}`,cohort.timeZone,'plum')}${stat('Enrollment',`${cohort.enrolledCount} / ${cohort.capacity}`,'Participants enrolled','green')}${stat('Investment',money(cohort.price),'Per participant','ochre')}${stat('Status',cohort.status,'Twelve-week group coaching','orange')}</div><section class="panel">${panelHead(isCoach()||isBuyer()?'Participant roster':'Your enrollment','Invited → enrolled → completed',isCoach()?button('Invite participants +','bulk-invite',id):'')}${table(['Participant','Email','Enrollment',...(isCoach()?['Update']:[])],roster.map(item=>`<tr><td><strong>${e(who(item.userId))}</strong></td><td>${e(app.data.users.find(u=>u.id===item.userId)?.email || '')}</td><td>${badge(item.status)}</td>${isCoach()?`<td><select aria-label="Enrollment for ${e(who(item.userId))}" data-enrollment="${e(item.id)}">${['invited','enrolled','completed','withdrawn'].map(s=>`<option ${s===item.status?'selected':''}>${s}</option>`).join('')}</select></td>`:''}</tr>`))}${!roster.length?'<p class="muted-copy">Invite the people who will do the work together.</p>':''}</section>${isBuyer()?evaluationSection(id):''}<section>${panelHead('Session schedule','Chronological, from baseline to integration')}<div class="session-list">${sessions.map(s=>sessionCard(s)).join('')}</div></section><section>${panelHead('Shared resources','Files available to your role',isCoach()?button('Upload a document +','upload-document',id):'')}<div class="card-grid">${docs.map(documentCard).join('')||empty('A place for the work','Preparation, reflections, and useful resources appear here.')}</div></section>`;
}
export function buyers() {
  return `${heading('People & accounts', isCoach()?'Buyer accounts':'Company profile','Company, contact, and billing details in one place.',isCoach()?button('Add a buyer +','new-buyer','','primary'):'')}<div class="card-grid">${app.data.buyers.map(buyer=>`<article class="cohort-card"><span class="eyebrow">Buyer account</span><h3>${e(buyer.company)}</h3><p>${e(buyer.contact)}<br/>${e(buyer.email)}</p><dl class="detail-list"><div><dt>Billing contact</dt><dd>${e(buyer.billingEmail)}</dd></div><div><dt>Billing address</dt><dd class="pre-wrap">${e(buyer.billingAddress||'Not provided')}</dd></div><div><dt>Cohorts</dt><dd>${app.data.cohorts.filter(c=>c.buyerId===buyer.id).length}</dd></div></dl><div class="card-actions">${button('Edit profile','edit-buyer',buyer.id)}${isCoach()?button('Invite buyer','invite-buyer',buyer.id,'quiet'):button('Message coach','message-coach',buyer.id,'quiet')}</div></article>`).join('')||empty('No buyer accounts yet','Add the company sponsoring your first program.')}</div>`;
}
export function sessions() {
  const list = scoped(app.data.sessions).sort((a,b)=>a.startsAt.localeCompare(b.startsAt));
  const upcoming = list.filter(s=>!['completed','cancelled'].includes(s.status)), past=list.filter(s=>['completed','cancelled'].includes(s.status));
  return `${heading('Scheduling & delivery','Sessions',`All times in ${timeZone()}. Joining opens 15 minutes before each session.`, !isCoach()&&!isBuyer()?button('Book a 1:1 ↗','book-one-to-one','','primary'):'')}<div class="session-list">${upcoming.map(s=>sessionCard(s)).join('')||empty('Your calendar is clear','Confirmed sessions appear here.')}</div>${past.length?`<section>${panelHead('Past sessions','Completed and cancelled sessions')}<div class="session-list">${past.map(s=>sessionCard(s,true)).join('')}</div></section>`:''}`;
}
export function availability() {
  return `${heading('Scheduling together','Availability','Participants rank their top five times. The coach reviews the responses and confirms the series.',isCoach()?button('Create an availability poll +','new-poll','','primary'):'')}<div class="card-grid">${scoped(app.data.polls).map(p=>{const mine=p.responses.find(r=>r.userId===app.data.user.id),expired=Date.parse(p.deadline)<Date.now();return `<article class="cohort-card"><div class="card-top"><span class="eyebrow">${e(cohortName(p.cohortId))}</span>${badge(p.status==='open'&&expired?'overdue':p.status)}</div><h3>${e(p.title)}</h3><p>Choose five of ${p.slots.length} proposed times.<br/>Response deadline: ${dt(p.deadline)}.</p><div class="poll-progress"><strong>${p.responseCount}</strong><span>responses received</span></div>${p.status==='confirmed'?`<p class="success-copy">Confirmed: ${dt(p.slots[p.winningIndex])} at ${time(p.slots[p.winningIndex])}</p>`:''}<div class="card-actions">${isCoach()?button('View response matrix','poll-matrix',p.id,'primary'):!isBuyer()&&p.status==='open'&&!expired?button(mine?'Update my preferences':'Rank my top five','respond-poll',p.id,'primary'):''}${mine?badge('responded'):''}</div></article>`;}).join('')||empty('No polls yet','Your coach will propose times for the cohort here.')}</div>`;
}
export function resources() {
  return `${heading('Documents & shared resources','Resource library','Preparation, readings, and shared files. Each document shows who can access it.',isCoach()?button('Upload a document +','upload-document','','primary'):'')}<div class="scope-legend">${['cohort','individual','buyer','private'].map(badge).join('')}</div><div class="card-grid">${scoped(app.data.documents).map(documentCard).join('')||empty('Your resource library is ready','Your coach will share preparation, readings, and follow-up materials here.')}</div>`;
}
export function reports() {
  return `${heading('Reporting & measurement','Reports & reflections','Individual reflections, cohort summaries, and a plan for what comes next.',!isBuyer()?button(isCoach()?'Compose a report +':'Write a reflection +','new-report','','primary'):'')}<div class="card-grid">${scoped(app.data.reports).map(reportCard).join('')||empty('Progress starts with a baseline','Published reports shared with your account appear here.')}</div>`;
}
export function surveys() {
  return `${heading('Pre / mid / post','Program surveys','Five-point reflections make progress visible across the program.',isCoach()?button('Create a survey +','new-survey','','primary'):'')}<div class="card-grid">${scoped(app.data.surveys).map(s=>{const mine=s.responses.find(r=>r.userId===app.data.user.id),closed=s.status!=='open'||Date.parse(s.deadline)<Date.now();return `<article class="cohort-card"><div class="card-top"><span class="eyebrow">${e(s.stage)}-program</span>${badge(s.status==='open'&&closed?'overdue':s.status)}</div><h3>${e(s.title)}</h3><p>${e(cohortName(s.cohortId))}<br/>Due ${dt(s.deadline)}</p><div class="poll-progress"><strong>${s.responseCount}</strong><span>reflections received</span></div><div class="card-actions">${isCoach()?button('View results','survey-results',s.id):isBuyer()?button('View aggregate results','survey-results',s.id):!closed?button(mine?'Update reflection':'Take the survey','respond-survey',s.id,'primary'):button('View my reflection','survey-results',s.id)}${isCoach()?button('Configure','edit-survey',s.id,'quiet'):mine?badge('responded'):''}</div></article>`;}).join('')||empty('No surveys available yet','Your coach can open a pre, mid, or post-program reflection.')}</div>`;
}
