import {app,e,field,check,panelHead,badge,button} from './ui.js';

export function zoomSettings(){
  const z=app.data.zoom||{},enabled=z.available&&!app.data.demo&&z.operationsAllowed;
  return `<section class="panel zoom-settings">${panelHead('Zoom','Video sessions, ready when your participants are.',badge(z.connected?'connected':'not-connected'))}
    <div class="settings-form"><div class="zoom-path"><span class="eyebrow">For Calendly bookings · easiest setup</span><h3>Connect Zoom through Calendly</h3><p>Authorize Zoom in Calendly, then choose Zoom as the location for your discovery and 1:1 event types. With Calendly booking sync enabled, GoCoach receives the meeting link automatically.</p><a class="btn" href="https://calendly.com/integrations/zoom" target="_blank" rel="noopener noreferrer">Open Zoom setup in Calendly ↗</a><p class="help">No code or additional credentials in GoCoach. Calendly manages these meetings; GoCoach does not create a duplicate.</p></div></div>
    <form data-form="zoom" class="settings-form"><span class="eyebrow">For sessions scheduled in GoCoach</span><h3>Connect a Zoom host directly</h3><p>Create and update Zoom meetings for cohort sessions from their session cards.</p>
      <details class="zoom-guide"><summary>First-time setup · no code required</summary><ol><li>Sign in to <a href="https://marketplace.zoom.us/" target="_blank" rel="noopener noreferrer">Zoom App Marketplace</a> as an account owner or admin.</li><li>Choose Develop → Build App → Server-to-Server OAuth. Give it a name, and complete the information.</li><li>Add the user and meeting scopes listed below, then copy the Account ID, Client ID, and Client Secret into this form. Activate the app.</li></ol><p class="help">A Zoom admin may need to allow app creation. <a href="https://developers.zoom.us/docs/internal-apps/create/" target="_blank" rel="noopener noreferrer">Zoom’s setup guide ↗</a></p><p class="help">Scopes: <code>user:read:user:admin</code>, <code>meeting:write:meeting:admin</code>, <code>meeting:read:meeting:admin</code>, <code>meeting:read:list_meetings:admin</code>, <code>meeting:update:meeting:admin</code>, <code>meeting:delete:meeting:admin</code>.</p></details>
      ${!z.available?'<p class="notice">Secure connection settings are available with PostgreSQL enabled.</p>':app.data.demo?'<p class="notice">Live Zoom credentials require a production workspace with coach sign-in.</p>':!z.operationsAllowed?'<p class="notice">Manage Zoom on the production site.</p>':''}
      <fieldset class="calendly-fields" ${!enabled?'disabled':''}><div class="form-grid">${field('Account ID','accountId','text',z.accountId||'','autocomplete="off" maxlength="200"')}${field('Client ID','clientId','text',z.clientId||'','autocomplete="off" maxlength="200"')}${field('Host’s Zoom email','hostEmail','email',z.hostEmail||'','autocomplete="off"')}</div>${field(z.secretConfigured?'Replace client secret (optional)':'Client secret','clientSecret','password','','autocomplete="new-password" maxlength="500"',!z.secretConfigured)}
      <p class="help">${z.secretConfigured?'A client secret is stored. Leave this blank to keep it.':'Your client secret will be encrypted on the server.'} Access tokens are handled automatically; you never need to edit code.</p>${!z.secretStorageReady&&z.available?'<p class="help">The deployer must set GOCOACH_SECRET_KEY once before connecting providers.</p>':''}${check('Enable the waiting room for new meetings','waitingRoom',z.waitingRoom!==false)}<div class="card-actions"><button class="btn primary" type="submit">Save & test Zoom</button>${z.connected?button('Disconnect Zoom','zoom-disconnect','','quiet danger'):''}</div><p class="form-error" role="alert" hidden></p></fieldset>
      ${z.connected?`<p class="help">Connected host: ${e(z.hostName)} · ${e(z.hostEmail)}</p>`:''}<p class="help">Meetings use unique passcodes and recording is off. Your Zoom plan controls meeting limits. Disconnecting keeps existing meetings and join links.</p>
    </form><div class="zoom-scope"><strong>Included now</strong><p>Create a meeting, sync a changed time, remove a meeting, and open role-protected join links.</p><strong>Possible next steps</strong><p>Attendance, recordings, transcripts, and an embedded meeting room. These require additional permissions and are not enabled in this prototype.</p></div>
  </section>`;
}

export function zoomSessionActions(session){
  if(app.data.user.role!=='coach'||session.provider==='calendly')return '';
  const z=app.data.zoom||{},meeting=z.meetings?.find(m=>m.sessionId===session.id);
  if(!z.connected)return '';
  return `<div class="material-block"><span class="eyebrow">Zoom meeting</span><p>${meeting?'After changing this session’s time or title, sync Zoom to update the meeting.':'Create a meeting and add its join link to this session.'}</p><div class="card-actions">${session.status==='scheduled'&&(!session.hasMeetingUrl||meeting)?button(meeting?'Sync Zoom meeting':'Create Zoom meeting','zoom-sync',session.id,'primary'):''}${meeting?button('Remove Zoom meeting','zoom-remove',session.id,'quiet danger'):''}</div>${session.status==='cancelled'&&meeting?'<p class="notice">This session is cancelled in GoCoach. Remove its Zoom meeting as well.</p>':''}</div>`;
}
